apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-check-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox-cron
            image: ikulyk404/busyboxplus:curl
            command: ["curl", "-s", "http://todo-service/api/health/"]
            resources:
              requests:
                memory: "16Mi"
                cpu: "10m"
              limits:
                memory: "32Mi"
                cpu: "50m"
          restartPolicy: OnFailure